txt = {
	"firstname":{"fr":"Prénom"},
	"lastname":{"fr":"Nom"},
	"email":{"fr":"Email"},
	"phone":{"fr":"Téléphone"},
	"phone1":{"fr":"Téléphone 1"},
	"phone2":{"fr":"Téléphone 2"},
	"address":{"fr":"Adresse"},
	"title" : {"fr":"Titre"},
	"price_15":{"fr":"Prix derniere quinzaine"},
	"price_30": {"fr":"Prix mois"},
	"level": {"fr":"Niveau"},
	"discount": {"fr":"Remise"},
	"user": {"fr":"Client"},
	"price_duration": {"fr":"Type d'abonnement"},
	"price":{"fr":"Prix"},
	"total_price":{"fr":"Prix total"},
	"selected_period":{"fr":"Mois concerné"},
	"payment_date":{"fr":"Date de paiement"},
}